from util import *
Import('*')

found = True
buildName = 'IRLUtil'
trueName = 'IRL Utilities Library'


conf = Configure(env.Clone())
if not env.GetOption('clean'):
    printInfo('Configuring ' + trueName)
    # Check For Librarys
    print 'Nothing to Check'   
build = conf.Finish()

if found:
    if not env.GetOption('clean'):
        printSuccess(trueName + ' is being built')
    sources = ["util.cpp"
            ]
    libutil = build.SharedLibrary(buildName,sources)


    build.Install(lib_dir, libutil)
    build.Alias(buildName, libutil)
else:
     printError(trueName + ' is not being built')
if not env.GetOption('clean'):
    print ''
