Import('*')

print 'Adding Devices and Main Program'


SConscript("Device/SConscript", exports='env lib_dir bin_dir')


SConscript("Programs/SConscript",
           exports="env lib_dir bin_dir")

SConscript("thirdparty/SConscript",exports="env lib_dir bin_dir")

SConscript("util/SConscript",exports="env lib_dir bin_dir")
